//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Momentum.BackOffice.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Momentum.BackOffice.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cm_Cancel {
            get {
                return ResourceManager.GetString("cm_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string cm_Save {
            get {
                return ResourceManager.GetString("cm_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing period (minutes).
        /// </summary>
        internal static string pr_OptionsViewModel_BillingPeriodMinutes {
            get {
                return ResourceManager.GetString("pr_OptionsViewModel_BillingPeriodMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date tolerance (seconds).
        /// </summary>
        internal static string pr_OptionsViewModel_DateToleranceSeconds {
            get {
                return ResourceManager.GetString("pr_OptionsViewModel_DateToleranceSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking free minutes.
        /// </summary>
        internal static string pr_OptionsViewModel_FreeMinutes {
            get {
                return ResourceManager.GetString("pr_OptionsViewModel_FreeMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum minutes to charge.
        /// </summary>
        internal static string pr_OptionsViewModel_MinimumMinutesToCharge {
            get {
                return ResourceManager.GetString("pr_OptionsViewModel_MinimumMinutesToCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes to exit.
        /// </summary>
        internal static string pr_OptionsViewModel_MinutesToExit {
            get {
                return ResourceManager.GetString("pr_OptionsViewModel_MinutesToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking places.
        /// </summary>
        internal static string pr_OptionsViewModel_ParkingCapacity {
            get {
                return ResourceManager.GetString("pr_OptionsViewModel_ParkingCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per hour.
        /// </summary>
        internal static string pr_OptionsViewModel_PricePerHour {
            get {
                return ResourceManager.GetString("pr_OptionsViewModel_PricePerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price rounding decimals.
        /// </summary>
        internal static string pr_OptionsViewModel_PriceRoundDecimals {
            get {
                return ResourceManager.GetString("pr_OptionsViewModel_PriceRoundDecimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Devices Code.
        /// </summary>
        internal static string pr_OptionsViewModel_TestDevicesCode {
            get {
                return ResourceManager.GetString("pr_OptionsViewModel_TestDevicesCode", resourceCulture);
            }
        }
    }
}
